import {BarChart3, Brain, Mic, ShieldAlert, UserCircle2, Video} from "lucide-react";

export const features = [
    {
        icon: Brain,
        badge: "Core",
        title: "AI-Powered Interviews",
        description:
            "Deep conversational intelligence that adapts its questioning style, difficulty, and depth in real-time — just like a seasoned interviewer would.",
        accent: "#6EE7B7",
        span: "col-span-2",
    },
    {
        icon: UserCircle2,
        badge: "Personas",
        title: "Custom Interviewer Personas",
        description:
            "Build unlimited personas — define the role, company culture, domain, and experience level. The AI embodies each persona completely.",
        accent: "#93C5FD",
        span: "col-span-1",
    },
    {
        icon: Video,
        badge: "Real-time",
        title: "Audio & Video Calls",
        description:
            "Live WebRTC-powered interview sessions. Speak your answers out loud; the AI listens, transcribes, and responds naturally.",
        accent: "#F9A8D4",
        span: "col-span-1",
    },
    {
        icon: ShieldAlert,
        badge: "Integrity",
        title: "Cheating Detection",
        description:
            "Tab-switch tracking, multi-speaker audio detection, and face-count analysis — every session is proctored so your results mean something.",
        accent: "#FCA5A5",
        span: "col-span-1",
    },
    {
        icon: Mic,
        badge: "Voice",
        title: "Speech Analysis",
        description:
            "Filler-word detection, pacing, and confidence scoring layered on top of your transcribed answers for a full vocal performance breakdown.",
        accent: "#C4B5FD",
        span: "col-span-1",
    },
    {
        icon: BarChart3,
        badge: "Insights",
        title: "AI Performance Reports",
        description:
            "Post-interview reports generated by the AI: answer quality, response time, red flags, and targeted coaching to close the gap.",
        accent: "#FDE68A",
        span: "col-span-2",
    },
];